name: scrape

on:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches:
      - master

jobs:
  scrape:
    runs-on: ubuntu-latest
    container: python:3.7
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Checkout data
        uses: actions/checkout@v2
        with:
          ref: 'data'
          path: 'data_branch/'
      - name: Scrape
        run: |
          SCRAPE_DATETIME=$(date +'%Y-%m-%dT%T')
          SCRAPE_DATE=$(date +'%Y-%m-%d')
          python scrape.py data_branch $SCRAPE_DATETIME
          cd data_branch
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "scrape $SCRAPE_DATETIME" --date $SCRAPE_DATETIME
          git tag $SCRAPE_DATE
          git push
          git push origin $SCRAPE_DATE -f
